server:
  port: 8080



# mapper.xml文件路径
mybatis:
  mapper-locations: classpath:mapping/*.xml

spring:
  datasource:
    name: miaosha
    url: jdbc:mysql://127.0.0.1:3306/miaosha
    username: root
    password: admin
    #使用 druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver

  jpa: show-sql=true

  mvc:
    throw-exception-if-no-handler-found: true

  resources:
    add-mappings: false

#配置redis
  redis:
    host: 127.0.0.1
    port: 6379
    database: 10
    jedis:
      pool:
        max-active: 50
        min-idle: 20


#日志配置
logging:
  level:
    root: debug